# Generated by Django 6.0.2 on 2026-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='followers', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
